# Generated by Django 4.0.4 on 2022-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indigenas',
            fields=[
                ('cedula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('etnia', models.CharField(max_length=30)),
                ('casta', models.CharField(max_length=30)),
                ('grado_instruccion', models.CharField(choices=[('primaria', 'Primaria'), ('segundaria', 'Seundaria'), ('universitario', 'Universitario')], max_length=14)),
                ('fecha_de_nacimiento', models.DateTimeField()),
                ('estado_de_salud', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'censo de indigena',
            },
        ),
    ]
